name: Build QAFAX Desktop Executable

on:
  push:
    branches: ["main"]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: utf-8
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install \
            pyinstaller \
            PySide6 \
            Pillow \
            numpy \
            pdf2image \
            opencv-python \
            scikit-image \
            pytesseract \
            pyzbar \
            pyserial \
            smbprotocol \
            pywin32

      - name: Run unit tests
        run: python -m unittest

      - name: Build executable
        run: pyinstaller scripts/qafax_desktop.spec

      - name: Verify executable output
        shell: pwsh
        run: |
          if (-not (Test-Path dist/QAFAXDesktop.exe)) {
            Write-Error "Expected dist/QAFAXDesktop.exe but it was not produced"
          }

      - name: Upload workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: QAFAXDesktop-${{ github.run_id }}
          path: dist/QAFAXDesktop.exe
          retention-days: 14

      - name: Publish release asset
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/QAFAXDesktop.exe
